### ISSUE TITLE
possible missing pkl file in goolge drive

### ISSUE THREAD

**Issue by 634085586** [KIMGEONUNG/BigColor#13]
it seems that args.pkl is not in google drive.
I am not able to find args.pkl from checkpoint folder in google drive

**Comment by KIMGEONUNG** [comment]
![image](https://github.com/KIMGEONUNG/BigColor/assets/32098205/57dc2cd4-6b28-4787-a626-82f046581837)

In ckpts folder in google drive, could you see the list like the above?

**Comment by 634085586** [comment]
I can see the file now after opening the folder, thank you very much!
