### ISSUE TITLE
download pretrained model fail！

### ISSUE THREAD

**Issue by coallar** [KIMGEONUNG/BigColor#4]
Hi, it seems to fail to download pretrained model use ./download-bigcolor.sh, return error like this:

requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1iQ2OAnQRAqd-6PDtQCrqh5-L_F_GXpq4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4fb862ac18>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

**Comment by KIMGEONUNG** [comment]
Now I'm checking the issue.
Instead of the download script, please use the google drive link below for download.

https://drive.google.com/drive/folders/1nLzgE5WJnxp5WF1dkpa1ts6bZ6tVwtep?usp=sharing

If the link does not work, please let me know.

**Comment by coallar** [comment]
> https://drive.google.com/drive/folders/1nLzgE5WJnxp5WF1dkpa1ts6bZ6tVwtep?usp=sharing

THANKS

**Comment by AlexanderKozhevin** [comment]
@coallar sorry, were you able to launch the script for colorization?
