### ISSUE TITLE
FileNotFoundError: ./ckpts/baseline_1000/EG_000.ckpt

### ISSUE THREAD

**Issue by techhalloman** [KIMGEONUNG/BigColor#5]
$ python colorize.py
Target Epoch is 000
Traceback (most recent call last):
  File "colorize.py", line 172, in <module>
    main(args)
  File "colorize.py", line 58, in main
    raise FileNotFoundError(path_eg)
FileNotFoundError: ./ckpts/baseline_1000/EG_000.ckpt

**Comment by KIMGEONUNG** [comment]
I don't know what you want.

Please carefully read the "README.MD".

If you want to colorize an arbitrary image.
Run the command below in bash.
```
./scripts/colorize.real.sh
```

Before trying to colorize, you should download the pretrained model, as described in README.MD

**Comment by AlexanderKozhevin** [comment]
@TechHalloman hello, sorry, were you able to launch colorization?

**Comment by techhalloman** [comment]
sorry recently my system crashed... anable to this... thank you i will try. 
https://www.youtube.com/channel/UCjW9D5sNP_vxI8DHa56Qqyw ... i like this channel
