### ISSUE TITLE
Black and white video colorization

### ISSUE THREAD

**Issue by nass2020** [KIMGEONUNG/BigColor#7]
Hello, congratulations for this work, 
how can I colorize a black and white video with this python code? 
I could not get the result of a colorized image in %04d.png output, 

how can I use each pre-trained model separately with %04d.png output? to use ffmpeg to get the result in video.mp4
Looking forward to your reply, please accept my best regards.

**Comment by KIMGEONUNG** [comment]
Thank you for your attention on our work.

To reply your question, at first, if you want to colorize a video, you have to extract all frame from video file, colorize each frame using the "colorize_real.py" script, and convert all colorized frames into a video file. There are so many example codes for video-to-frames and frames-to-video, so you can easily find that with googling.

If my answer is not what you want, please let me know.

**Comment by nass2020** [comment]
> Thank you for your attention on our work.
> 
> To reply your question, at first, if you want to colorize a video, you have to extract all frame from video file, colorize each frame using the "colorize_real.py" script, and convert all colorized frames into a video file. There are so many example codes for video-to-frames and frames-to-video, so you can easily find that with googling.
> 
> If my answer is not what you want, please let me know.

Hello Thank you very much for your answer, I managed to colorize all the images in the video, but the concern, that each image is colorized in 3 times with 3 different models with an output (name + '_c%03d.jpg), I would like the image this colorized with a single model and a single result with an output (%03d. jpg), so I can use this command (!ffmpeg -f image2 -framerate 24 -i /content/BigColor/results_real/%03d.jpg -c:v h264_nvenc -preset slow -qp 18 -pix_fmt yuv420p output2.mp4 ) to get the result of a colorized video, thank you again for this amazing work.

**Comment by nass2020** [comment]
**in this output colorized image (name + '_c%03d.jpg), I was not able to transform the images to a video.**

![alt text](https://i.ibb.co/VDW0qrW/Sans-titre4.png)
**I would like the result of the colorized images to be in this forma %03d.jpg, for i use this command (!ffmpeg -f image2 -framerate 24 -i /content/BigColor/results_real/%03d.jpg -c:v h264_nvenc -preset slow -qp 18 -pix_fmt yuv420p output2.mp4 )**

![alt text](https://i.ibb.co/7KGJ04F/Sans-titre.png)

**Comment by KIMGEONUNG** [comment]
[Here](https://github.com/KIMGEONUNG/BigColor/tree/nass2020)  is a code branch for you.
When you use the code of the branch, the one solution would be estimated for each input image, and the file name has no _c000 format.

If it is hard to change the code branch for you, just replace the file colorize_real.py with this https://github.com/KIMGEONUNG/BigColor/blob/nass2020/colorize_real.py

More specifically, I just edited the codes related to file name and the number of inferences.
If any other issues remain, please let me know.

**Comment by nass2020** [comment]
> [Here](https://github.com/KIMGEONUNG/BigColor/tree/nass2020) is a code branch for you. When you use the code of the branch, the one solution would be estimated for each input image, and the file name has no _c000 format.
> 
> If it is hard to change the code branch for you, just replace the file colorize_real.py with this https://github.com/KIMGEONUNG/BigColor/blob/nass2020/colorize_real.py
> 
> More specifically, I just edited the codes related to file name and the number of inferences. If any other issues remain, please let me know.

thank you very much for your answer, now I can have colorized %03d. jpg images to make an mp4 output, here is the result it's amazing: https://drive.google.com/file/d/1CNMRfWRHRwEV6e6CzrJCdy-xrdesEg61/view?usp=sharing

the only problem is that i couldn't get a stable color, is there any way to correct this please? if so, this would be the best colorizer i've seen so far.

Thank you very much for this phenomenal work, I look forward to your response, best regards

**Comment by KIMGEONUNG** [comment]
Unfortunately, our colorization method cannot sustain temporal color consistency, which is our future work.
Again, thank you very much your attention.
